spring:
  application:
    name: batch-explorer
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    #    url: jdbc:h2:file:./build/testdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  #  h2:
#    console:
#      enabled: true
  batch:
    jdbc:
      initialize-schema: always